### PR TITLE
ExpressBrute.js

### PR DESCRIPTION
**Pull request by ghost**
In this file the code on line 44
it('correctly calculates delays', function () {
			brute.delays.should.deep.equal([10,10,20,30,50,80,100]);
		});

The Fibonacci sequence is incorrect instead of 100 there should be 130 .

### CODE REVIEW

**Review by toufik-airane — COMMENTED** [review]
Dear @godzkid,

The contribution doesn't meet our quality requirements. 🚫
Thanks.

**Review by JamieSlome — COMMENTED** [review]
This doesn't look like a fix that solves the issue. Feel free to make more commits! 🍰

**Comment by ghost** [comment]
💙💙💙we will try our best

**Comment by huntr-helper** [comment]
Sorry @godzkid, we enjoyed reviewing your fix but it has not been selected this time. If this bounty has not been closed, please feel free to try again with a new pull request! We appreciate your effort and look forward to reviewing more of your fixes in the future! :hammer: :sunglasses:

**Pull request closed without merging**
